name: Publish
on:
  push:
    branches:
      - main

jobs:
   build:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tischreservierung
          password: ${{ secrets.GHCR_LOGIN }}
          
      - name: Build and publish Container
        run: |
          docker build . -t ghcr.io/tischreservierung/frontend:latest
          docker push ghcr.io/tischreservierung/frontend:latest
