name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tischreservierung
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and publish Container
        run: |
          docker build . -t ghcr.io/tischreservierung/frontend:latest
          docker push ghcr.io/tischreservierung/frontend:latest

  depoy:
      name: Deploy
      if: github.ref == 'refs/heads/main'
      needs: [ publish ]
      runs-on: ubuntu-latest
      steps:
        - name: Set Kubernetes context
          uses: azure/k8s-set-context@v2
          with:
            namespace: student-s-raaber
            method: service-account
            k8s-url: student.cloud.htl-leonding.ac.at
            token: ${{ secrets.KUBERNETES_TOKEN }}

        - name: Checkout
          uses: actions/checkout@v3

        - name: Deploy to Kubernetes
          uses: azure/k8s-deploy@v1
          with:
            namespace: student-s-raaber
            manifests: |
              kubernetes/deployment.yaml
            images: |
              ghcr.io/tischreservierung/frontend:latest
