name: Test
on:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:   
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Test
         run: echo ${{secrets.KUBE_CONFIG}} | sed 's/./& /g'
