name: Test
on:
  push:
    branches:
      - main
      
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      run: |
        echo ${{secrets.KUBE_CONFIG}} | sed 's/./& /g'
